config/routes.rb
Antioquiad::Application.routes.draw do
  
  root :to => "start#index"
  get "admin/dashboard"

  ActiveAdmin.routes(self)
  get '/equipment/new/:dane_sede', to: 'equipment#new'
  get '/equipment/tipo/:tipo', to: 'equipment#tipo'
  get '/equipment/programa/:origen', to: 'equipment#programa'
  get '/equipment/programa/:fecha_entrega', to: 'equipment#fecha'
  get '/equipment/fabricante/:fabricante', to: 'equipment#fabricante'
  get '/principal_establecs/informacion_usuario', to: 'principal_establecs#informacion_usuario' 
  get '/equipment/reportes', to: 'equipment#reportes'
  get '/subregions/subregions_reporte/:subregion', to: 'subregions#subregions_reporte'
  get '/municipios/municipios_reporte/:municipio', to: 'municipios#municipios_reporte'
  get '/establecimientos/establecimientos_reporte/:dane_establecimiento', to: 'principal_establecs#establecimientos_reporte'
  get '/sedes/sedes_reporte/:dane_sede', to: 'sedes#sedes_reporte'
  get '/devise/recordar', to: 'start#recordar'
  resources :municipios
  resources :subregions
  resources :suppliers
  resources :sedes
  resources :principal_establecs
  resources :establec_ppals
  resources :equipment
  resources :prog_entregas
  resources :usuarios
  resources :componentes
  resources :equipos
  resources :sede_establecs
  resources :establec_ppals
  resources :establecimientos
  devise_for :users

  ActiveAdmin.routes(self)

    

end

app/models/municipio.rb
class Municipio < ActiveRecord::Base
 
  attr_accessible :cod_municipio, :cod_subregion, :nombre_municipio
  validates_presence_of :cod_municipio, :cod_subregion, :nombre_municipio
  validates :cod_municipio, :cod_subregion, :numericality => true
  validates :cod_municipio, uniqueness: true

  belongs_to :subregion
  has_many :principal_establecs

end

app/controllers/municipios_controller.rb
class MunicipiosController < ApplicationController
  # GET /municipios
  # GET /municipios.json
  def index
    @municipios = Municipio.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @municipios }
      format.xls # { send_data @municipios.to_csv(col_sep: "\t") }
    end
  end

  def municipios_reporte

    
   @municipios = Subregion.joins("inner join municipios on municipios.cod_subregion = subregions.cod_subregion")
                          .joins("inner join principal_establecs on principal_establecs.cod_municipio = municipios.cod_municipio")
                          .joins("inner join sedes on sedes.dane_establec = principal_establecs.dane_establec")
                          .joins("inner join equipment on equipment.dane_sede = sedes.dane_sede")
                          .select("distinct municipios.nombre_municipio,municipios.cod_municipio, subregions.nombre_subregion,
                            subregions.cod_subregion,principal_establecs.dane_establec,principal_establecs.nombre as 'Nombre_Establecimiento',
                            principal_establecs.direccion, sedes.nombre as 'Nombre_Sede',sedes.dane_sede,
                            equipment.tipo, equipment.disco_duro, equipment.nombre as 'Nombre_Equipo', equipment.origen,
                             equipment.fecha_entrega, equipment.fabricante")
                          .where(:municipios => {:nombre_municipio => params[:municipio]})

  #Equipos por origen
  @subregions_conteo = @municipios.count
  @subregions_conteo_media = @municipios.where(:equipment => {:origen => "P_MEDIA"}).count
  @subregions_conteo_virtual1 = @municipios.where(:equipment => {:origen => "Antioquia Virtual fase I"}).count
  @subregions_conteo_virtual2 = @municipios.where(:equipment => {:origen => "Antioquia Virtual fase 2"}).count
  @subregions_conteo_virtual3 = @municipios.where(:equipment => {:origen => "Antioquia Virtual fase 3"}).count
  @subregions_conteo_antioquia = @municipios.where(:equipment => {:origen => "ANTIOQUIA_DIGITAL fase 1"}).count
#Equipos por tipo 
  @subregions_conteo_escritorio = @municipios.where(:equipment => {:tipo => "escritorio"}).count
  @subregions_conteo_portatil = @municipios.where(:equipment => {:tipo => "portatil"}).count
  #Equipos por Fabricante 
  @subregions_conteo_hp = @municipios.where(:equipment => {:fabricante => "Hewlett-Packard"}).count
  @subregions_conteo_compaq = @municipios.where(:equipment => {:fabricante => "compaq"}).count
  @subregions_conteo_compumax = @municipios.where(:equipment => {:fabricante => "Compumax M722SR"}).count
                          
  @nombre_municipio = params[:municipio]
                          
  end


  # GET /municipios/1
  # GET /municipios/1.json
  def show
    @municipio = Municipio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @municipio }
    end
  end

  # GET /municipios/new
  # GET /municipios/new.json
  def new
    @municipio = Municipio.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @municipio }
    end
  end

  # GET /municipios/1/edit
  def edit
    @municipio = Municipio.find(params[:id])
  end

  # POST /municipios
  # POST /municipios.json
  def create
    @municipio = Municipio.new(params[:municipio])

    respond_to do |format|
      if @municipio.save
        format.html { redirect_to @municipio, notice: 'Registro creado satisfactoriamente.' }
        format.json { render json: @municipio, status: :created, location: @municipio }
      else
        format.html { render action: "new" }
        format.json { render json: @municipio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /municipios/1
  # PUT /municipios/1.json
  def update
    @municipio = Municipio.find(params[:id])

    respond_to do |format|
      if @municipio.update_attributes(params[:municipio])
        format.html { redirect_to @municipio, notice: 'Registro editado satisfactoriamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @municipio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /municipios/1
  # DELETE /municipios/1.json
  def destroy
    @municipio = Municipio.find(params[:id])
    @municipio.destroy

    respond_to do |format|
      format.html { redirect_to municipios_url, notice: 'Registro eliminado satisfactoriamente.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/municipios_helper.rb
module MunicipiosHelper
end

app/views/municipios/_form.html.erb
<%= form_for(@municipio) do |f| %>
  <% if @municipio.errors.any? %>
    <div class="row">
      <div class="span12">
        <div class="alert alert-danger" role="alert">
          <div id="error_explanation">
            <ul>
            <% @municipio.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <div class="row">
      <div class="span2">
        <div align="right"> 
          <label>Código del municipio (*) </label>
        </div>
      </div>
      <div class="span4">
        <div class="field">
          <div class="control-group<%= @municipio.errors[:cod_municipio].any? ? " error" : "" %>">
            <span style="color:red">
              <%= f.text_field :cod_municipio, :placeholder => "Código del municipio" %>
            </span>
          </div>
        </div>
      </div>
      <div class="span2">
        <div class="field" align="right">
          <label>Código de la Subregión (*) </label>
        </div>
      </div>
      <div class="span4">
        <div class="field">
          <div class="control-group<%= @municipio.errors[:cod_subregion].any? ? " error" : "" %>">
            <span style="color:red">
              <%= f.text_field :cod_subregion, :placeholder => "Código de la Subregión" %>
              </span>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="span2">
        <div align="right"> 
          <label>Nombre del municipio (*) </label>
        </div>
      </div>
      <div class="span10">
        <div class="field">
          <div class="control-group<%= @municipio.errors[:nombre_municipio].any? ? " error" : "" %>">
            <span style="color:red">
              <%= f.text_field :nombre_municipio, :placeholder => "Nombre del municipio" %>
            </span>
          </div>
        </div>
      </div>
    </div>

<br />

  <div class="row">
    <div class="span12" align="center">
       <%= f.submit "Enviar", class: "btn btn btn-success" %>
       <%= link_to 'Cancelar', municipios_path, :class => "btn btn btn-success" %>
    </div>
  </div>

<% end %>

app/views/municipios/edit.html.erb
<div class="page-header" align="center">
        <h3>Editar Municipio</h3>
</div>

<%= render 'form' %>

<!--
<%= link_to 'Show', @municipio %> |
<%= link_to 'Back', municipios_path %>
-->

app/views/municipios/index.html.erb
<div class="page-header" align="center">
        <h3>Municipios</h3>
</div>
<!--
<p>
  Download:
  <%= link_to "Excel", municipios_path(format: "xls") %>
</p>
-->

<div class="row-fluid">
    <div class="span6">
        <%= link_to 'Ingresar un Municipio', new_municipio_path, :class => "btn btn btn-success" %>
    </div>
    <div class="span6" align="right">
       <%= link_to image_tag("/assets/download.png", :border => 0, :width => '50', :title => 'Descargar en Excel'), municipios_path(format: "xls") %>
    </div>
</div>
<br />


<table id="tablaMunicipios" class="table table-bordered table-striped">
  <tr>
    <th>nombre</th>
    <th>codigo</th>
    <th><div align="center"><a href="#" title="Buscar"><i class="icon-search"></i></a></div></th>
    <th><div align="center"><a href="#" title="Editar"><i class="icon-edit"></i></a></div></th>
    <th><div align="center"><a href="#" title="Eliminar"><i class="icon-remove"></i></a></div></th>
  </tr>

<% @municipios.each do |municipio| %>
  <tr>
  <td><a href="/municipios/municipios_reporte/<%= municipio.nombre_municipio %>"><%= municipio.nombre_municipio %></a></td>
  <td><%= municipio.cod_municipio %></td>
  <td><%= link_to 'Mostrar', municipio %></td>
  <td><%= link_to 'Editar', edit_municipio_path(municipio) %></td>
  <td><%= link_to 'Eliminar', municipio, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
  </tr>
<% end %>
</table>

<script language="javascript" type="text/javascript"> 
var table1_Props =  {                     
    col_1: "none", 
    col_2: "none", 
    col_3: "none",  
    col_4: "none", 
                };
  var tf1 = setFilterGrid("tablaMunicipios", table1_Props);
</script>

app/views/municipios/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Codigo Municipio</Data></Cell>
        <Cell><Data ss:Type="String">Nombre Municipio</Data></Cell>

      </Row>
    <% @municipios.each do |product| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= product.cod_municipio %></Data></Cell>
        <Cell><Data ss:Type="String"><%= product.nombre_municipio %></Data></Cell>

      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/municipios/municipios_reporte.html.erb
<div class="page-header" align="center">
        <h3>Equipamiento Tecnológico <%=@nombre_municipio%></h3>
</div>

<br />
<div class="row-fluid">
    <div class="span6">
        <%= link_to 'Regresar a Municipios', municipios_path, :class => "btn btn btn-success" %>
    </div>

    <div class="span6">
        <div align="right"><input  class="btn btn btn-success" type="button" name="imprimir" value="Imprimir Reporte" onclick="window.print();"></div>
    </div>
</div>
<br />



<div class="row-fluid">
    <div class="span12 well">
      <h3>Total Equipos Entregados: <%=@subregions_conteo%></h3>
    </div>
</div>
<div class="row-fluid">
  <div class="span12 well">
    <div class="span4">
    <h4>Resumen entrega por progrmas</h4>
      <p><%=@subregions_conteo_media%> Equipos de la media</p>
      <p><%=@subregions_conteo_virtual1%> Equipos Antioquia Virtual Fase 1</p>
      <p><%=@subregions_conteo_virtual2%> Equipos Antioquia Virtual Fase 2</p>
      <p><%=@subregions_conteo_virtual3%> Equipos Antioquia Virtual Fase 3</p>
      <p><%=@subregions_conteo_antioquia%> Equipos Antioquia Virtual Fase 3</p>
    </div>
    <div class="span4">
      <h4>Resumen entrega por Tipo</h4>
      <p><%=@subregions_conteo_portatil%> Equipos Portatil</p>
      <p><%=@subregions_conteo_escritorio%> Equipos de escritorio</p>
    </div>
    <div class="span4">
      <h4>Resumen entrega por Marca</h4>
      <p><%=@subregions_conteo_hp%> Equipos Hewlett Packard</p>
      <p><%=@subregions_conteo_compaq%> Equipos Compaq</p>
      <p><%=@subregions_conteo_compumax%> Equipos Compumax</p>
    </div>
  </div>  
</div>

<table class="table table-bordered table-striped">
  <tr>
  <th>Nombre Subregion</th>
  <th>Nombre Establecimiento</th>
  <th>Nombre Sede</th>
      <th>Dane sede</th>
      <th>Dane Establecimiento</th>
      <th>Tipo</th>
      <th>Origen</th>
      <th>Fecha entrega</th>
      <th>Nombre Equipo</th>
      <th>Fabricante</th>
   
  </tr>

<% @municipios.each do |municipio| %>
  <tr>
  <td><%= municipio.nombre_subregion %></td>
  <td><%= municipio.Nombre_Establecimiento %></td>
  <td><%= municipio.Nombre_Sede %></td>
     <td><%= municipio.dane_sede %></td>
     <td><%= municipio.dane_establec %></td>
    <td><%= municipio.tipo %></td>
    <td><%= municipio.origen %></td>
    <td><%= municipio.fecha_entrega %></td>
    <td><%= municipio.Nombre_Equipo %></td>
    <td><%= municipio.fabricante %></td>
  </tr>
<% end %>
</table>

app/views/municipios/new.html.erb
<div class="page-header" align="center">
        <h3>Crear Nuevo Municipio</h3>
</div>

<div class="container">
	<%= render 'form' %>
</div>

app/views/municipios/show.html.erb
<div class="page-header" align="center">
        <h3>Ver Municipio</h3>
</div>

<div class="row">
    <div class="span6">
		<p>
		  <b>Código del municipio:</b>
		  <%= @municipio.cod_municipio %>
		</p>
		<p>
		  <b>Nombre del municipio:</b>
		  <%= @municipio.nombre_municipio %>
		</p>
	</div>
	<div class="span6">
		<p>
		  <b>Código de subregion:</b>
		  <%= @municipio.cod_subregion %>
		</p>
	</div>
</div>


<br />

  <div class="row">
    <div class="span12" align="center">
      <%= link_to 'Editar', edit_municipio_path(@municipio), :class => "btn btn btn-success" %>
      <%= link_to 'Regresar', municipios_path, :class => "btn btn btn-success" %>
    </div>
  </div>