config/routes.rb
Antioquiad::Application.routes.draw do
  
  root :to => "start#index"
  get "admin/dashboard"

  ActiveAdmin.routes(self)
  get '/equipment/new/:dane_sede', to: 'equipment#new'
  get '/equipment/tipo/:tipo', to: 'equipment#tipo'
  get '/equipment/programa/:origen', to: 'equipment#programa'
  get '/equipment/programa/:fecha_entrega', to: 'equipment#fecha'
  get '/equipment/fabricante/:fabricante', to: 'equipment#fabricante'
  get '/principal_establecs/informacion_usuario', to: 'principal_establecs#informacion_usuario' 
  get '/equipment/reportes', to: 'equipment#reportes'
  get '/subregions/subregions_reporte/:subregion', to: 'subregions#subregions_reporte'
  get '/municipios/municipios_reporte/:municipio', to: 'municipios#municipios_reporte'
  get '/establecimientos/establecimientos_reporte/:dane_establecimiento', to: 'principal_establecs#establecimientos_reporte'
  get '/sedes/sedes_reporte/:dane_sede', to: 'sedes#sedes_reporte'
  get '/devise/recordar', to: 'start#recordar'
  resources :municipios
  resources :subregions
  resources :suppliers
  resources :sedes
  resources :principal_establecs
  resources :establec_ppals
  resources :equipment
  resources :prog_entregas
  resources :usuarios
  resources :componentes
  resources :equipos
  resources :sede_establecs
  resources :establec_ppals
  resources :establecimientos
  devise_for :users

  ActiveAdmin.routes(self)

    

end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
  attr_accessible :dane_sede, :disco_duro, :display, :fabricante, :fecha_entrega, :memoria_ram, :modelo, :nombre, :origen, :procesador, :serial, :sist_operativo, :tipo
  validates_presence_of :dane_sede, :disco_duro, :display, :fabricante, :fecha_entrega, :memoria_ram, :modelo, :nombre, :origen, :procesador, :serial, :sist_operativo, :tipo
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
  # GET /equipment
  # GET /equipment.json
    def tipo
    if current_user.superadmin?
    @equipment = Equipment.where(tipo: params[:tipo])
    @equipment_conteo  = @equipment.count
    else
      @grab_dane_establecimiento = PrincipalEstablec.where(correo: current_user.email)
      @dane_establec= @grab_dane_establecimiento[0].dane_establec
      @grab_dane_sede = Sede.where(dane_establec: @dane_establec)
      @dane_sede = @grab_dane_sede[0].dane_sede
      @equipment = Equipment.where(dane_sede: [@dane_sede]).where(tipo: params[:tipo])
      @equipment_conteo  = @equipment.count

    end
  end

    def programa
    if current_user.superadmin?
       @equipment = Equipment.where(origen: params[:origen])
       @equipment_conteo  = @equipment.count
    else
      @grab_dane_establecimiento = PrincipalEstablec.where(correo: current_user.email)
      @dane_establec= @grab_dane_establecimiento[0].dane_establec
      @grab_dane_sede = Sede.where(dane_establec: @dane_establec)
      @dane_sede = @grab_dane_sede[0].dane_sede
      @equipment = Equipment.where(dane_sede: [@dane_sede]).where(origen: params[:origen])
      @equipment_conteo  = @equipment.count

    end
  end

   def reportes
    @equipment = Equipment.new
    #Municipios de una Subregion
    @municipios = Subregion.joins("inner join municipios mu on mu.cod_subregion = subregions.cod_subregion")
    .select("distinct mu.nombre_municipio").where(nombre_subregion: "NORTE")

    #Establecimientos de un Municipio
    @establecimientos = Municipio.joins("inner join principal_establecs pe on pe.cod_municipio = municipios.cod_municipio")
    .select("distinct pe.nombre").where(nombre_municipio: "DONMATIAS")

    #Sedes de un Establecimiento
    
    @sedes = PrincipalEstablec.joins("inner join sedes se on se.dane_establec = principal_establecs.dane_establec")
    .select("se.nombre").where(nombre: "CER_CHALI")

  end



  
    def fecha
    if current_user.superadmin?
       @equipment = Equipment.where(fecha_entrega: params[:fecha_entrega])
       @equipment_conteo  = @equipment.count
    else
      @grab_dane_establecimiento = PrincipalEstablec.where(correo: current_user.email)
      @dane_establec= @grab_dane_establecimiento[0].dane_establec
      @grab_dane_sede = Sede.where(dane_establec: @dane_establec)
      @dane_sede = @grab_dane_sede[0].dane_sede
      @equipment = Equipment.where(dane_sede: [@dane_sede]).where(fecha_entrega: params[:fecha_entrega])
      @equipment_conteo  = @equipment.count

    end
  end

    def fabricante
    if current_user.superadmin?
       @equipment = Equipment.where(fabricante: params[:fabricante])
       @equipment_conteo  = @equipment.count
    else
      @grab_dane_establecimiento = PrincipalEstablec.where(correo: current_user.email)
      @dane_establec= @grab_dane_establecimiento[0].dane_establec
      @grab_dane_sede = Sede.where(dane_establec: @dane_establec)
      @dane_sede = @grab_dane_sede[0].dane_sede
      @equipment = Equipment.where(dane_sede: [@dane_sede]).where(fabricante: params[:fabricante])
      @equipment_conteo  = @equipment.count

    end
  end

  def index
    if current_user.superadmin?
    @equipment = Equipment.all
    @equipment_conteo = Equipment.count unless @equipment.empty?
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @equipment }
      format.xls # { send_data @equipment.to_csv(col_sep: "\t") }
              end
    else
      @grab_dane_establecimiento = PrincipalEstablec.where(correo: current_user.email)
      @dane_establec= @grab_dane_establecimiento[0].dane_establec
      @grab_dane_sede = Sede.where(dane_establec: @dane_establec)
      @dane_sede = @grab_dane_sede[0].dane_sede
      @equipment = Equipment.where(dane_sede: [@dane_sede])
      @equipment_conteo  = @equipment.count
      @param_dane = Equipment.where(dane_sede: params[:dane_sede])  
     

    end
  end

  def show
    @equipment = Equipment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @equipment }
    end
  end

  # GET /equipment/new
  # GET /equipment/new.json
  def new
    @equipment = Equipment.new
    @param_dane =  params[:dane_sede]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @equipment }
    end
  end

  # GET /equipment/1/edit
  def edit
    @equipment = Equipment.find(params[:id])
  end

  # POST /equipment
  # POST /equipment.json
  def create
    @equipment = Equipment.new(params[:equipment])

    respond_to do |format|
      if @equipment.save
        format.html { redirect_to @equipment, notice: 'Registro creado satisfactoriamente.' }
        format.json { render json: @equipment, status: :created, location: @equipment }
      else
        format.html { render action: "new" }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /equipment/1
  # PUT /equipment/1.json
  def update
    @equipment = Equipment.find(params[:id])

    respond_to do |format|
      if @equipment.update_attributes(params[:equipment])
        format.html { redirect_to @equipment, notice: 'Registro editado satisfactoriamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipment/1
  # DELETE /equipment/1.json
  def destroy
    @equipment = Equipment.find(params[:id])
    @equipment.destroy

    respond_to do |format|
      format.html { redirect_to equipment_index_url, notice: 'Registro eliminado satisfactoriamente.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/views/equipment/edit.html.erb
<div class="page-header" align="center">
        <h3>Editar Equipos</h3>
</div>

<%= render 'form' %>

<!--
<%= link_to 'Show', @equipment %> |
<%= link_to 'Back', equipment_index_path %>
-->

app/views/equipment/fabricante.html.erb
<div class="page-header" align="center">
        <h3>Equipos por fabricante</h3>
</div>

<br />
<div class="row-fluid">
  <div class="span6 well">
    <strong>Cantidad Equipos: </strong> <%= @equipment_conteo %>
  </div>
        <div class="span6">
        <div align="right"><input  class="btn btn btn-success" type="button" name="imprimir" value="Imprimir Reporte" onclick="window.print();"></div>
    </div>
</div>

<% unless @equipment.empty?%>
<table class="table table-bordered table-striped">
  <tr>
    <th>Dane sede</th>
    <th>Tipo</th>
    <th>Origen</th>
    <th>Fecha entrega</th>
    <th>Nombre</th>
    <th>Fabricante</th>
    <!--
    <th>Modelo</th>
    <th>Serial</th>
    <th>Procesador</th>
    <th>Memoria ram</th>
    <th>Disco duro</th>
    <th>Display</th>
    <th>Sist operativo</th>
    -->
    <th><div align="center"><a href="#" title="Buscar"><i class="icon-search"></i></a></div></th>
    <th><div align="center"><a href="#" title="Editar"><i class="icon-edit"></i></a></div></th>
    <th><div align="center"><a href="#" title="Eliminar"><i class="icon-remove"></i></a></div></th>
  </tr>

<% @equipment.each do |equipment| %>
  <tr>
    <td><%= equipment.dane_sede %></td>
    <td><%= equipment.tipo %></td>
    <td><%= equipment.origen %></td>
    <td><%= equipment.fecha_entrega %></td>
    <td><%= equipment.nombre %></td>
    <td><%= equipment.fabricante.gsub(/\s+/, "") %></td>
    <!--
    <td><%= equipment.modelo %></td>
    <td><%= equipment.serial %></td>
    <td><%= equipment.procesador %></td>
    <td><%= equipment.memoria_ram %></td>
    <td><%= equipment.disco_duro %></td>
    <td><%= equipment.display %></td>
    <td><%= equipment.sist_operativo %></td>
    -->
    <td><%= link_to 'Mostrar', equipment %></td>
    <td><%= link_to 'Editar', edit_equipment_path(equipment) %></td>
    <td><%= link_to 'Eliminar', equipment, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
  </tr>
<% end %>
<% else%>
<p>ESTABLECIMIENTO SIN EQUIPOS REGISTRADOS</p>
<% end %>

</table>

<br />

<%= link_to 'New Equipment', new_equipment_path %>

app/views/equipment/index.html.erb
<div class="page-header" align="center">
        <h3>Equipamiento</h3>
</div>

<p>
  Download:
  <a href="/equipment.xls">excel</a>
</p>



<div class="row-fluid">
    <div class="span6">
        <%= link_to 'Crear nuevo', new_equipment_path, :class => "btn btn btn-success" %>
    </div>
        <div class="span6">
        <div align="right"><input  class="btn btn btn-success" type="button" name="imprimir" value="Imprimir Reporte" onclick="window.print();"></div>
    </div>

</div>

<br />
<div class="row-fluid">
  <div class="span12 well">
    <strong>Cantidad Equipos: </strong> <%= @equipment_conteo %>
  </div>
</div>

<% unless @equipment.empty?%>
<table class="table table-bordered table-striped">
  <tr>
    <th>Dane sede</th>
    <th>Tipo</th>
    <th>Origen</th>
    <th>Fecha entrega</th>
    <th>Nombre</th>
    <th>Fabricante</th>
    <!--
    <th>Modelo</th>
    <th>Serial</th>
    <th>Procesador</th>
    <th>Memoria ram</th>
    <th>Disco duro</th>
    <th>Display</th>
    <th>Sist operativo</th>
    -->
    <th><div align="center"><a href="#" title="Buscar"><i class="icon-search"></i></a></div></th>
    <th><div align="center"><a href="#" title="Editar"><i class="icon-edit"></i></a></div></th>
    <th><div align="center"><a href="#" title="Eliminar"><i class="icon-remove"></i></a></div></th>
  </tr>

<% @equipment.each do |equipment| %>
  <tr>
   <td> <a href="/equipment/new/<%= equipment.dane_sede %>"><%= equipment.dane_sede %></a></td>
    <td><%= equipment.tipo %></td>
    <td><%= equipment.origen %></td>
    <td><%= equipment.fecha_entrega %></td>
    <td><%= equipment.nombre %></td>
    <td><%= equipment.fabricante %></td>
    <!--
    <td><%= equipment.modelo %></td>
    <td><%= equipment.serial %></td>
    <td><%= equipment.procesador %></td>
    <td><%= equipment.memoria_ram %></td>
    <td><%= equipment.disco_duro %></td>
    <td><%= equipment.display %></td>
    <td><%= equipment.sist_operativo %></td>
    -->
    <td><%= link_to 'Mostrar', equipment %></td>
    <td><%= link_to 'Editar', edit_equipment_path(equipment) %></td>
    <td><%= link_to 'Eliminar', equipment, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
  </tr>
<% end %>
<% else%>
    <p>ESTABLECIMIENTO SIN EQUIPOS REGISTRADOS</p>
<% end %>

</table>

app/views/equipment/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Codigo dane</Data></Cell>
        <Cell><Data ss:Type="String">disco_duro</Data></Cell>
        <Cell><Data ss:Type="String">fecha_entrega</Data></Cell>
        <Cell><Data ss:Type="String">memoria_ram</Data></Cell>
        <Cell><Data ss:Type="String">nombre</Data></Cell>
      </Row>
    <% @equipment.each do |product| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= product.dane_sede %></Data></Cell>
        <Cell><Data ss:Type="String"><%= product.disco_duro %></Data></Cell>
        <Cell><Data ss:Type="String"><%= product.fecha_entrega %></Data></Cell>
        <Cell><Data ss:Type="String"><%= product.nombre %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/equipment/new.html.erb
<div class="page-header" align="center">
        <h3>Ingresar Equipo</h3>
</div>

<%= render 'form' %>

<%= link_to 'Back', equipment_index_path %>

app/views/equipment/programa.html.erb
<div class="page-header" align="center">
        <h3>Equipos por programa</h3>
</div>

<div class="row-fluid">
  <div class="span6 well">
    <strong>Cantidad Equipos: </strong> <%= @equipment_conteo %>
  </div>
      <div class="span6">
        <div align="right"><input  class="btn btn btn-success" type="button" name="imprimir" value="Imprimir Reporte" onclick="window.print();"></div>
    </div>
</div>

<% unless @equipment.empty?%>
<table class="table table-bordered table-striped">
  <tr>
    <th>Dane sede</th>
    <th>Tipo</th>
    <th>Origen</th>
    <th>Fecha entrega</th>
    <th>Nombre</th>
    <th>Fabricante</th>
    <!--
    <th>Modelo</th>
    <th>Serial</th>
    <th>Procesador</th>
    <th>Memoria ram</th>
    <th>Disco duro</th>
    <th>Display</th>
    <th>Sist operativo</th>
    -->
    <th><div align="center"><a href="#" title="Buscar"><i class="icon-search"></i></a></div></th>
    <th><div align="center"><a href="#" title="Editar"><i class="icon-edit"></i></a></div></th>
    <th><div align="center"><a href="#" title="Eliminar"><i class="icon-remove"></i></a></div></th>
  </tr>

<% @equipment.each do |equipment| %>
  <tr>
    <td><%= equipment.dane_sede %></td>
    <td><%= equipment.tipo %></td>
    <td><%= equipment.origen %></td>
    <td><%= equipment.fecha_entrega %></td>
    <td><%= equipment.nombre %></td>
    <td><%= equipment.fabricante %></td>
    <!--
    <td><%= equipment.modelo %></td>
    <td><%= equipment.serial %></td>
    <td><%= equipment.procesador %></td>
    <td><%= equipment.memoria_ram %></td>
    <td><%= equipment.disco_duro %></td>
    <td><%= equipment.display %></td>
    <td><%= equipment.sist_operativo %></td>
    -->
    <td><%= link_to 'Mostrar', equipment %></td>
    <td><%= link_to 'Editar', edit_equipment_path(equipment) %></td>
    <td><%= link_to 'Eliminar', equipment, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
  </tr>
<% end %>
<% else%>
<p>ESTABLECIMIENTO SIN EQUIPOS REGISTRADOS</p>
<% end %>

</table>

<br />

<%= link_to 'New Equipment', new_equipment_path %>

app/views/equipment/reportes.html.erb
<%= form_tag do %> 
<%=select_tag(:sedes, :name) %>
<%end%>

app/views/equipment/show.html.erb
<div class="page-header" align="center">
        <h3>Ver Equipo</h3>
</div>

<div class="row">
  <div class="span6">
    <p>
      <b>Dane sede:</b>
      <%= @equipment.dane_sede %>
    </p>

    <p>
      <b>Tipo:</b>
      <%= @equipment.tipo %>
    </p>

    <p>
      <b>Origen:</b>
      <%= @equipment.origen %>
    </p>

    <p>
      <b>Fecha entrega:</b>
      <%= @equipment.fecha_entrega %>
    </p>

    <p>
      <b>Nombre:</b>
      <%= @equipment.nombre %>
    </p>

    <p>
      <b>Fabricante:</b>
      <%= @equipment.fabricante %>
    </p>
  </div>

  <div class="span6">
    <p>
      <b>Modelo:</b>
      <%= @equipment.modelo %>
    </p>

    <p>
      <b>Serial:</b>
      <%= @equipment.serial %>
    </p>

    <p>
      <b>Procesador:</b>
      <%= @equipment.procesador %>
    </p>

    <p>
      <b>Memoria ram:</b>
      <%= @equipment.memoria_ram %>
    </p>

    <p>
      <b>Disco duro:</b>
      <%= @equipment.disco_duro %>
    </p>

    <p>
      <b>Display:</b>
      <%= @equipment.display %>
    </p>

    <p>
      <b>Sist operativo:</b>
      <%= @equipment.sist_operativo %>
    </p>
  </div>
</div>

<br />

<div class="row">
  <div class="span12" align="center">
    <%= link_to 'Editar', edit_equipment_path(@equipment), :class => "btn btn btn-success" %>
    <%= link_to 'Regresar', equipment_index_path, :class => "btn btn btn-success" %>
  </div>
</div>

app/views/equipment/tipo.html.erb
<div class="page-header" align="center">
        <h3>Equipos por tipo de dispositivo</h3>
</div>
<br />

<div class="row-fluid">
  <div class="span6 well">
    <strong>Cantidad Equipos: </strong> <%= @equipment_conteo %>
  </div>
 <div class="span6">
        <div align="right"><input  class="btn btn btn-success" type="button" name="imprimir" value="Imprimir Reporte" onclick="window.print();"></div>
    </div>
</div>

<% unless @equipment.empty?%>
<table class="table table-bordered table-striped">
  <tr>
    <th>Dane sede</th>
    <th>Tipo</th>
    <th>Origen</th>
    <th>Fecha entrega</th>
    <th>Nombre</th>
    <th>Fabricante</th>
    <!--
    <th>Modelo</th>
    <th>Serial</th>
    <th>Procesador</th>
    <th>Memoria ram</th>
    <th>Disco duro</th>
    <th>Display</th>
    <th>Sist operativo</th>
    -->
    <th><div align="center"><a href="#" title="Buscar"><i class="icon-search"></i></a></div></th>
    <th><div align="center"><a href="#" title="Editar"><i class="icon-edit"></i></a></div></th>
    <th><div align="center"><a href="#" title="Eliminar"><i class="icon-remove"></i></a></div></th>
  </tr>

<% @equipment.each do |equipment| %>
  <tr>
    <td><%= equipment.dane_sede %></td>
    <td><%= equipment.tipo %></td>
    <td><%= equipment.origen %></td>
    <td><%= equipment.fecha_entrega %></td>
    <td><%= equipment.nombre %></td>
    <td><%= equipment.fabricante %></td>
    <!--
    <td><%= equipment.modelo %></td>
    <td><%= equipment.serial %></td>
    <td><%= equipment.procesador %></td>
    <td><%= equipment.memoria_ram %></td>
    <td><%= equipment.disco_duro %></td>
    <td><%= equipment.display %></td>
    <td><%= equipment.sist_operativo %></td>
    -->
    <td><%= link_to 'Mostrar', equipment %></td>
    <td><%= link_to 'Editar', edit_equipment_path(equipment) %></td>
    <td><%= link_to 'Eliminar', equipment, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
  </tr>
<% end %>
<% else%>
<p>ESTABLECIMIENTO SIN EQUIPOS REGISTRADOS</p>
<% end %>

</table>

<br />

<%= link_to 'New Equipment', new_equipment_path %>

app/views/equipment/user_information.html.erb
<div class="page-header" align="center">
        <h3>Listado de Equipos</h3>
</div>

<table class="table table-bordered table-striped">
  <tr>
    <th>Dane sede</th>
    <th>Tipo</th>
    <th>Origen</th>
    <th><div align="center"><a href="#" title="Buscar"><i class="icon-search"></i></a></div></th>
    <th><div align="center"><a href="#" title="Editar"><i class="icon-edit"></i></a></div></th>
    <th><div align="center"><a href="#" title="Eliminar"><i class="icon-remove"></i></a></div></th>
  </tr>


<% @principal_establecs.each do |usuario| %>
  <tr>
    <td><%= usuario.email %></td>
    
 </tr>
 </table>
 <%end%>

<%= link_to 'New User', new_user_path %>

app/views/equipment/usuarios.html.erb
<% unless @usuarios.empty?%>
<table class="table table-bordered table-striped">
  <tr>
    <th>Dane sede</th>
    <th>Tipo</th>
    <th>Origen</th>
    <th>Fecha entrega</th>
    <th>Nombre</th>
    <th>Fabricante</th>
    <!--
    <th>Modelo</th>
    <th>Serial</th>
    <th>Procesador</th>
    <th>Memoria ram</th>
    <th>Disco duro</th>
    <th>Display</th>
    <th>Sist operativo</th>
    -->
    <th><div align="center"><a href="#" title="Buscar"><i class="icon-search"></i></a></div></th>
    <th><div align="center"><a href="#" title="Editar"><i class="icon-edit"></i></a></div></th>
    <th><div align="center"><a href="#" title="Eliminar"><i class="icon-remove"></i></a></div></th>
  </tr>

<% @usuarios.each do |equipment| %>
  <tr>
    <td><%= equipment.dane_sede %></td>
    <td><%= equipment.tipo %></td>