config/routes.rb
Antioquiad::Application.routes.draw do
  
  root :to => "start#index"
  get "admin/dashboard"

  ActiveAdmin.routes(self)
  get '/equipment/new/:dane_sede', to: 'equipment#new'
  get '/equipment/tipo/:tipo', to: 'equipment#tipo'
  get '/equipment/programa/:origen', to: 'equipment#programa'
  get '/equipment/programa/:fecha_entrega', to: 'equipment#fecha'
  get '/equipment/fabricante/:fabricante', to: 'equipment#fabricante'
  get '/principal_establecs/informacion_usuario', to: 'principal_establecs#informacion_usuario' 
  get '/equipment/reportes', to: 'equipment#reportes'
  get '/subregions/subregions_reporte/:subregion', to: 'subregions#subregions_reporte'
  get '/municipios/municipios_reporte/:municipio', to: 'municipios#municipios_reporte'
  get '/establecimientos/establecimientos_reporte/:dane_establecimiento', to: 'principal_establecs#establecimientos_reporte'
  get '/sedes/sedes_reporte/:dane_sede', to: 'sedes#sedes_reporte'
  get '/devise/recordar', to: 'start#recordar'
  resources :municipios
  resources :subregions
  resources :suppliers
  resources :sedes
  resources :principal_establecs
  resources :establec_ppals
  resources :equipment
  resources :prog_entregas
  resources :usuarios
  resources :componentes
  resources :equipos
  resources :sede_establecs
  resources :establec_ppals
  resources :establecimientos
  devise_for :users

  ActiveAdmin.routes(self)

    

end

app/models/principal_establec.rb
class PrincipalEstablec < ActiveRecord::Base
	
  attr_accessible :calendario, :correo, :dane_establec, :direccion, :jornada, :localidad, :nombre, :rector, :telefono, :zona, :cod_municipio
  validates_presence_of :calendario, :dane_establec, :localidad, :rector, :nombre, :correo, :direccion, :jornada, :telefono
  validates :dane_establec, :length => { :is => 12 }
  validates :dane_establec, :telefono, :numericality => true
  validates :dane_establec, uniqueness: true

  has_many :sedes
end

app/controllers/principal_establecs_controller.rb
class PrincipalEstablecsController < ApplicationController
  # GET /principal_establecs
  # GET /principal_establecs.json
  def establecimientos_reporte

   @establecimientos = Subregion.joins("inner join municipios on municipios.cod_subregion = subregions.cod_subregion")
                          .joins("inner join principal_establecs on principal_establecs.cod_municipio = municipios.cod_municipio")
                          .joins("inner join sedes on sedes.dane_establec = principal_establecs.dane_establec")
                          .joins("inner join equipment on equipment.dane_sede = sedes.dane_sede")
                          .select("distinct municipios.nombre_municipio,municipios.cod_municipio, subregions.nombre_subregion,
                            subregions.cod_subregion,principal_establecs.dane_establec,principal_establecs.nombre as 'Nombre_Establecimiento',
                            principal_establecs.direccion, sedes.nombre as 'Nombre_Sede',sedes.dane_sede,
                            equipment.tipo, equipment.disco_duro, equipment.nombre as 'Nombre_Equipo', equipment.origen,
                             equipment.fecha_entrega, equipment.fabricante")
                          .where(:principal_establecs => {:dane_establec => params[:dane_establecimiento]})

  #Equipos por origen
  @subregions_conteo = @establecimientos.count
  @subregions_conteo_media = @establecimientos.where(:equipment => {:origen => "P_MEDIA"}).count
  @subregions_conteo_virtual1 = @establecimientos.where(:equipment => {:origen => "Antioquia Virtual fase I"}).count
  @subregions_conteo_virtual2 = @establecimientos.where(:equipment => {:origen => "Antioquia Virtual fase 2"}).count
  @subregions_conteo_virtual3 = @establecimientos.where(:equipment => {:origen => "Antioquia Virtual fase 3"}).count
  @subregions_conteo_antioquia = @establecimientos.where(:equipment => {:origen => "ANTIOQUIA_DIGITAL fase 1"}).count
#Equipos por tipo 
  @subregions_conteo_escritorio = @establecimientos.where(:equipment => {:tipo => "escritorio"}).count
  @subregions_conteo_portatil = @establecimientos.where(:equipment => {:tipo => "portatil"}).count
  #Equipos por Fabricante 
  @subregions_conteo_hp = @establecimientos.where(:equipment => {:fabricante => "Hewlett-Packard"}).count
  @subregions_conteo_compaq = @establecimientos.where(:equipment => {:fabricante => "compaq"}).count
  @subregions_conteo_compumax = @establecimientos.where(:equipment => {:fabricante => "Compumax M722SR"}).count                        
  end

  def index
    if current_user.superadmin?
    @principal_establecs = PrincipalEstablec.all
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @principal_establec }
        format.xls # { send_data @products.to_csv(col_sep: "\t") }
      end
    else
      @join_sedes = Sede.joins('INNER JOIN principal_establecs ON  principal_establecs.dane_establec = sedes.dane_establec').where(correo: current_user.email)
      @join_establecimientos = PrincipalEstablec.joins('INNER JOIN sedes ON  sedes.dane_establec = principal_establecs.dane_establec').where(correo: current_user.email)
      @dane= @join_establecimientos[0].dane_establec
      @principal_establecs = PrincipalEstablec.where(dane_establec: @dane)
    end
    @join = Sede.joins('INNER JOIN principal_establecs pr ON  pr.dane_establec = sedes.dane_establec').where(correo: current_user.email)
  end

  # GET /principal_establecs/1
  # GET /principal_establecs/1.json
  def show
    @principal_establec = PrincipalEstablec.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @principal_establec }
    end
  end

  # GET /principal_establecs/new
  # GET /principal_establecs/new.json
  def new
    @principal_establec = PrincipalEstablec.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @principal_establec }
    end
  end

  # GET /principal_establecs/1/edit
  def edit
    @principal_establec = PrincipalEstablec.find(params[:id])
  end

  # POST /principal_establecs
  # POST /principal_establecs.json
  def create
    @principal_establec = PrincipalEstablec.new(params[:principal_establec])

    respond_to do |format|
      if @principal_establec.save
        format.html { redirect_to @principal_establec, notice: 'Registro creado satisfactoriamente.' }
        format.json { render json: @principal_establec, status: :created, location: @principal_establec }
      else
        format.html { render action: "new" }
        format.json { render json: @principal_establec.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /principal_establecs/1
  # PUT /principal_establecs/1.json
  def update
    @principal_establec = PrincipalEstablec.find(params[:id])

    respond_to do |format|
      if @principal_establec.update_attributes(params[:principal_establec])
        format.html { redirect_to @principal_establec, notice: 'Registro editado satisfactoriamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @principal_establec.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /principal_establecs/1
  # DELETE /principal_establecs/1.json
  def destroy
    @principal_establec = PrincipalEstablec.find(params[:id])
    @principal_establec.destroy

    respond_to do |format|
      format.html { redirect_to principal_establecs_url, notice: 'Registro eliminado satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  def informacion_usuario
    if current_user.superadmin?
          @usuarios = Subregion.joins("inner join municipios on municipios.cod_subregion = subregions.cod_subregion")
                          .joins("inner join principal_establecs on principal_establecs.cod_municipio = municipios.cod_municipio")
                          .joins("inner join sedes on sedes.dane_establec = principal_establecs.dane_establec")
                          .select(" distinct municipios.nombre_municipio, subregions.nombre_subregion
                            ,principal_establecs.dane_establec,principal_establecs.nombre as 'Nombre_Establecimiento',
                            principal_establecs.direccion,principal_establecs.correo,sedes.nombre as 'Nombre_Sede',sedes.dane_sede")
    else
          @usuarios = Subregion.joins("inner join municipios on municipios.cod_subregion = subregions.cod_subregion")
                          .joins("inner join principal_establecs on principal_establecs.cod_municipio = municipios.cod_municipio")
                          .joins("inner join sedes on sedes.dane_establec = principal_establecs.dane_establec")
                          .select("distinct municipios.nombre_municipio, subregions.nombre_subregion
                            ,principal_establecs.dane_establec,principal_establecs.nombre as 'Nombre_Establecimiento',
                            principal_establecs.direccion,principal_establecs.correo
                            ,sedes.nombre as 'Nombre_Sede',sedes.dane_sede")
                            .where(:principal_establecs => {:correo => current_user.email })


    end

  end

end

app/helpers/principal_establecs_helper.rb
module PrincipalEstablecsHelper
end

app/views/principal_establecs/_form.html.erb
<%= form_for (@principal_establec), :validate => :true do |f| %>
  <% if @principal_establec.errors.any? %>
  <div class="row">
    <div class="span12">
    <div class="alert alert-danger" role="alert">
      <div id="error_explanation">
        <!---
        <h2><%= pluralize(@principal_establec.errors.count, "error") %> prohibited this principal_establec from being saved:</h2>
        -->
        <ul>
        <% @principal_establec.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
      </div>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="span2">
      <div align="right"> 
        <label>Código Dane (*) </label>
      </div>
    </div>
    <div class="span4">
      <div class="field">
        <div class="control-group<%= @principal_establec.errors[:dane_establec].any? ? " error" : "" %>">
          <span style="color:red">
            <%= f.text_field :dane_establec, :placeholder => "Código dane" %>
          </span>
        </div>
      </div>
    </div>
    <div class="span2">
      <div class="field" align="right">
        <label>Localidad (*) </label>
      </div>
    </div>
    <div class="span4">
      <div class="field">
        <div class="control-group<%= @principal_establec.errors[:localidad].any? ? " error" : "" %>">
          <span style="color:red">
            <%= f.text_field :localidad, :placeholder => "Localidad" %>
            </span>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="span2">
      <div align="right"> 
        <label>Nombre del Rector (*) </label>
      </div>
    </div>
    <div class="span4">
      <div class="field"> 
        <div class="control-group<%= @principal_establec.errors[:rector].any? ? " error" : "" %>">
          <span style="color:red">
            <%= f.text_field :rector, :placeholder => "Nombre del rector" %>
            </span>
        </div>
      </div>
    </div>
    <div class="span2">
      <div class="field" align="right">
        <label>Nombre de la Institución (*) </label>
      </div>
    </div>
    <div class="span4">
      <div class="field">
        <div class="control-group<%= @principal_establec.errors[:nombre].any? ? " error" : "" %>">
          <span style="color:red">
            <%= f.text_field :nombre, :placeholder => "Nombre de la institución" %>
            </span>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="span2">
      <div align="right"> 
        <label>Zona (*) </label>
      </div>
    </div>
    <div class="span4">
      <div class="field"> 
          <div class="field">
            <% zonas = {"RURAL" => "RURAL", "URBANA" => "URBANA", "RURAL,URBANA" => "RURAL,URBANA"} %>
              <% lista = zonas.sort %>
              <%= f.select :zona, lista %>
          </div>
      </div>
    </div>
    <div class="span2">
      <div class="field" align="right">
        <label>Calendario (*) </label>
      </div>
    </div>
    <div class="span4">
      <div class="field">
        <div class="control-group<%= @principal_establec.errors[:calendario].any? ? " error" : "" %>">
          <span style="color:red">
            <%= f.text_field :calendario, :placeholder => "Calendario" %>
          </span>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="span2">
      <div align="right"> 
        <label>Jornada (*) </label>
      </div>
    </div>
    <div class="span4">
      <div class="field">
        <div class="control-group<%= @principal_establec.errors[:jornada].any? ? " error" : "" %>">
          <span style="color:red">
            <%= f.text_field :jornada, :placeholder => "Jornada" %>
            </span>
        </div>
      </div>
    </div>
    <div class="span2">
      <div class="field" align="right">
        <label>Dirección (*) </label>
      </div>
    </div>
    <div class="span4">
      <div class="field">
        <div class="control-group<%= @principal_establec.errors[:direccion].any? ? " error" : "" %>">
          <span style="color:red">
            <%= f.text_field :direccion, :placeholder => "Dirección" %>
            </span>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="span2">
      <div align="right"> 
        <label>Teléfono (*) </label>
      </div>
    </div>
    <div class="span4">
      <div class="field"> 
        <div class="control-group<%= @principal_establec.errors[:telefono].any? ? " error" : "" %>">
          <span style="color:red">
            <%= f.text_field :telefono, :placeholder => "Teléfono" %>
            </span>
        </div>
      </div>
    </div>
    <div class="span2">
      <div class="field" align="right">
        <label>Correo electrónico (*) </label>
      </div>
    </div>
    <div class="span4">
      <div class="field">
        <div class="control-group<%= @principal_establec.errors[:correo].any? ? " error" : "" %>">
          <span style="color:red">
            <%= f.text_field :correo, :placeholder => "Correo electrónico", :pattern => "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$" %>
            </span>
        </div>
      </div>
    </div>
  </div>

<br />

  <div class="row">
    <div class="span12" align="center">
       <%= f.submit "Enviar", class: "btn btn btn-success" %>
       <%= link_to 'Cancelar', principal_establecs_path, :class => "btn btn btn-success" %>
    </div>
  </div>

<% end %>

app/views/principal_establecs/edit.html.erb
<div class="page-header" align="center">
        <h3>Editar Establecimiento</h3>
</div>

<%= render 'form' %>

<!--
<%= link_to 'Show', @principal_establec %> |
<%= link_to 'Back', principal_establecs_path %>
-->

app/views/principal_establecs/establecimientos_reporte.html.erb
<div class="page-header" align="center">
        <h3>Establecimiento</h3>
</div>

<br />
<div class="row-fluid">
    <div class="span6">
        <%= link_to 'Regresar a establecimientos', principal_establecs_path, :class => "btn btn btn-success" %>
    </div>
    <div class="span6">
        <div align="right"><input  class="btn btn btn-success" type="button" name="imprimir" value="Imprimir Reporte" onclick="window.print();"></div>
    </div>
</div>
<br />

<div class="page-header">
  <h3>Reporte de totales</h3>
</div>
<br />

<div class="row-fluid">
  <div class="span12 well">
    <div class="span6">
      <p><%=@subregions_conteo%> Total Equipos en la subregión</p>
      <p><%=@subregions_conteo_media%> Equipos de la media en la subregión</p>
      <p><%=@subregions_conteo_virtual1%> Equipos Antioquia Virtual Fase 1 en la subregión</p>
      <p><%=@subregions_conteo_virtual2%> Equipos Antioquia Virtual Fase 2 en la subregión</p>
      <p><%=@subregions_conteo_virtual3%> Equipos Antioquia Virtual Fase 3 en la subregión</p>
    </div>
    <div class="span6">
      <p><%=@subregions_conteo_antioquia%> Equipos Antioquia Digital Fase 1 en la subregión</p>
      <p><%=@subregions_conteo_escritorio%> Equipos de escritorio en la subregión</p>
      <p><%=@subregions_conteo_portatil%> Equipos portátil en la subregión</p>
      <p><%=@subregions_conteo_hp%> Equipos Hewlett Packard en la subregión</p>
      <p><%=@subregions_conteo_compaq%> Equipos Compaq en la subregión</p>
      <p><%=@subregions_conteo_compumax%> Equipos Compumax en la subregión</p>
    </div>
  </div>  
</div>

<table class="table table-bordered table-striped">
  <tr>
  <th>Nombre Subregion</th>
  <th>Nombre Sede</th>
  <th>Nombre Establecimiento</th>
    <th>Dane sede</th>
    <th>Tipo</th>
    <th>Origen</th>
    <th>Fecha entrega</th>
    <th>Nombre</th>
    <th>Fabricante</th>
   
  </tr>

<% @establecimientos.each do |equipment| %>
  <tr>
  <td><%= equipment.nombre_subregion %></td>
  <td><%= equipment.Nombre_Sede %></td>
  <td><%= equipment.Nombre_Establecimiento %></td>
    <td><%= equipment.dane_sede %></td>
    <td><%= equipment.tipo %></td>
    <td><%= equipment.origen %></td>
    <td><%= equipment.fecha_entrega %></td>
    <td><%= equipment.Nombre_Equipo %></td>
    <td><%= equipment.fabricante %></td>
  </tr>
<% end %>
</table>

app/views/principal_establecs/index.html.erb
<div class="page-header" align="center">
        <h3>Establecimientos</h3>
</div>
<!--
<p>
  Download:
  <%= link_to "Excel", principal_establecs_path(format: "xls") %>
</p>
-->
<div class="row-fluid">
    <div class="span6">
        <%= link_to 'Ingresar un nuevo Establecimiento', new_principal_establec_path, :class => "btn btn btn-success" %>
    </div>
    <div class="span6" align="right">
       <%= link_to image_tag("/assets/download.png", :border => 0, :width => '50', :title => 'Descargar en Excel'), principal_establecs_path(format: "xls") %>
    </div>
</div>
<br />

<div class="row-fluid">
    <div class="span12">
        <table id="tablaEstablecimientos" class="table table-bordered table-striped">
          <tr>
            <th>Codigo dane</th>
            <!--
            <th>Localidad</th>
            -->
            <th>Insitución</th>
            <th>Rector</th>
            <!--
            <th>Zona</th>
            <th>Calendario</th>
            <th>Jornada</th>
            <th>Direccion</th>
            <th>Telefono</th>
            <th>Correo</th>
            -->
            <th><div align="center"><a href="#" title="Buscar"><i class="icon-search"></i></a></div></th>
            <th><div align="center"><a href="#" title="Editar"><i class="icon-edit"></i></a></div></th>
            <th><div align="center"><a href="#" title="Eliminar"><i class="icon-remove"></i></a></div></th>
          </tr>

          
        <% @principal_establecs.each do |principal_establec| %>
          <tr>
            
            <td><a href="/establecimientos/establecimientos_reporte/<%= principal_establec.dane_establec %>"><%= principal_establec.dane_establec %></a></td>
            <!--
            <td><%= principal_establec.localidad %></td>
            -->
            <td><%= principal_establec.nombre %></td>
            <td><%= principal_establec.rector %></td>
            <!--
            <td><%= principal_establec.zona %></td>
            <td><%= principal_establec.calendario %></td>
            <td><%= principal_establec.jornada %></td>
            <td><%= principal_establec.direccion %></td>
            <td><%= principal_establec.telefono %></td>
            <td><%= principal_establec.correo %></td>
            -->
            <td><%= link_to 'Mostrar', principal_establec %></td>
            <td><%= link_to 'Editar', edit_principal_establec_path(principal_establec) %></td>
            <td><%= link_to 'Eliminar', principal_establec, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
          </tr>
        <% end %>
        </table>
    </div>
</div>

<script language="javascript" type="text/javascript"> 
  var table1_Props =  {                     
    col_0: "none", 
    col_2: "none", 
    col_3: "none", 
    col_4: "none",  
    col_5: "none", 
                };
  var tf1 = setFilterGrid("tablaEstablecimientos", table1_Props);
</script>

app/views/principal_establecs/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Codigo dane</Data></Cell>
        <Cell><Data ss:Type="String">Nombre Sede</Data></Cell>
        <Cell><Data ss:Type="String">Direccion</Data></Cell>
        <Cell><Data ss:Type="String">Jornada</Data></Cell>
      </Row>
    <% @principal_establecs.each do |product| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= product.dane_establec %></Data></Cell>
        <Cell><Data ss:Type="String"><%= product.nombre %></Data></Cell>
        <Cell><Data ss:Type="String"><%= product.direccion %></Data></Cell>
        <Cell><Data ss:Type="String"><%= product.jornada %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/principal_establecs/informacion_usuario.html.erb
<table class="table table-bordered table-striped">
  <tr>
  <th>Nombre Subregion</th>
  <th>Nombre Municipio</th>
  <th>Nombre Establecimiento</th>
  <th>Dane Establecimiento</th>
    <th>Correo Electrònico</th>

   
  </tr>

<% @usuarios.each do |equipment| %>
  <tr>
	  <td><%= equipment.nombre_subregion %></td>
	  <td><%= equipment.nombre_municipio %></td>
	  <td><%= equipment.Nombre_Establecimiento %></td>
	  <td><%= equipment.dane_establec %></td>
	  <td><%= equipment.correo %></td>
  </tr>
<% end %>
</table>

app/views/principal_establecs/new.html.erb
<div class="page-header" align="center">
        <h3>Crear Nuevo Establecimiento</h3>
</div>

<div class="container">
	<%= render 'form' %>
</div>

app/views/principal_establecs/show.html.erb
<div class="page-header" align="center">
        <h3>Ver Establecimiento</h3>
</div>

<div class="row">
    <div class="span6">
      <p>
        <b>Código dane:</b>
        <%= @principal_establec.dane_establec %>
      </p>

      <p>
        <b>Localidad:</b>
        <%= @principal_establec.localidad %>
      </p>

      <p>
        <b>Nombre del Rector:</b>
        <%= @principal_establec.rector %>
      </p>

      <p>
        <b>Nombre de la Institución:</b>
        <%= @principal_establec.nombre %>
      </p>

      <p>
        <b>Zona:</b>
        <%= @principal_establec.zona %>
      </p>
    </div>
    <div class="span6">
      <p>
        <b>Calendario:</b>
        <%= @principal_establec.calendario %>
      </p>

      <p>
        <b>Jornada:</b>
        <%= @principal_establec.jornada %>
      </p>

      <p>
        <b>Direccion:</b>
        <%= @principal_establec.direccion %>
      </p>

      <p>
        <b>Telefono:</b>
        <%= @principal_establec.telefono %>
      </p>

      <p>
        <b>Correo:</b>
        <%= @principal_establec.correo %>
      </p>
    </div>
  </div>

<br />

  <div class="row">
    <div class="span12" align="center">
      <%= link_to 'Editar', edit_principal_establec_path(@principal_establec), :class => "btn btn btn-success" %>
      <%= link_to 'Regresar', principal_establecs_path, :class => "btn btn btn-success" %>
    </div>
  </div>